### ISSUE TITLE
Documentation on how to set it all up

### ISSUE THREAD

**Issue by Rovanion** [raymcdermott/reptile-tongue#3]
Hi again!

I know all of this is sort of pre-release still, but I would really like to set this up on my own machine to share a repl with my friends. So if it's not too much work could you write up some installation instructions?

If not instructions then perhaps requirements. i know there is tongue which delivers a package of HTML, CSS and JS to the web browser; is this package static content the only thing that tongue does or does it have any dynamic behaviour? Then there is tail which if I've understood correctly has a HTTP and WS server; is it then possible to run the two of them on the same subdomain or do I need two due to overlaps in request paths?

Thank you for writing this at all, really want to run it myself!

**Comment by raymcdermott** [comment]
Thanks for your enthusiasm! 

I have made quite some bug fixes in the past few days so it's probably good that the instructions are not yet ready 😬 

This coming week I'm going to do a little work on setting it up with [ngrok](https://ngrok.com) as I think that will be a straightforward option for many people.

**Comment by Rovanion** [comment]
No worries!

Such instructions should include enough information for me to derive an equivalent nginx conf.

**Comment by raymcdermott** [comment]
I'm going to close this now as everything can be run from the CLI and with ngrok
